language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip
install:
    - pip install -r requirements.txt

script:
    - python tests/my_tests.py

# after_success:

branches:
    only:
        - master
